services:
  - docker

before_install:
  - docker build -t shayoo/angular-with-docker .

script:
  - echo "run tests here"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shayoo/angular-with-docker
